package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String, val flag: String) {
    SYSTEM("system", "Sistem / Otomatik", "System Default", "🌐"),
    TR("tr", "Türkçe", "Türkçe", "🇹🇷"),
    EN("en", "İngilizce", "English", "🇬🇧"),
    ES("es", "İspanyolca", "Español", "🇪🇸"),
    DE("de", "Almanca", "Deutsch", "🇩🇪"),
    FR("fr", "Fransızca", "Français", "🇫🇷"),
    IT("it", "İtalyanca", "Italiano", "🇮🇹"),
    PT("pt", "Portekizce", "Português", "🇵🇹"),
    RU("ru", "Rusça", "Русский", "🇷🇺"),
    ZH("zh", "Çince", "中文", "🇨🇳"),
    JA("ja", "Japonca", "日本語", "🇯🇵"),
    KO("ko", "Korece", "한국어", "🇰🇷"),
    AR("ar", "Arapça", "العربية", "🇸🇦"),
    HI("hi", "Hintçe", "हिन्दी", "🇮🇳"),
    AZ("az", "Azerbaycanca", "Azərbaycan", "🇦🇿"),
    NL("nl", "Felemenkçe", "Nederlands", "🇳🇱"),
    PL("pl", "Lehçe", "Polski", "🇵🇱"),
    UK("uk", "Ukraynaca", "Українська", "🇺🇦"),
    ID("id", "Endonezce", "Bahasa Indonesia", "🇮🇩"),
    VI("vi", "Vietnamca", "Tiếng Việt", "🇻🇳")
}

data class TranslationStrings(
    val appTitle: String,
    // Tabs
    val tabCreate: String,
    val tabScan: String,
    val tabHistory: String,
    
    // Theme & Language
    val changeTheme: String,
    val changeLanguage: String,
    val autoDetectLanguage: String,
    val selectLanguageTitle: String,

    // Create Screen
    val createQrTitle: String,
    val qrTypeUrl: String,
    val qrTypeText: String,
    val qrTypeWifi: String,
    val qrTypePhone: String,
    val qrTypeEmail: String,
    val qrTypeSms: String,
    val websiteUrlLabel: String,
    val textContentLabel: String,
    val wifiSsidLabel: String,
    val wifiPasswordLabel: String,
    val wifiSecurityLabel: String,
    val wifiNone: String,
    val phoneNumberLabel: String,
    val emailToLabel: String,
    val emailSubjectLabel: String,
    val emailBodyLabel: String,
    val smsPhoneLabel: String,
    val smsMessageLabel: String,
    val appearanceAndLogo: String,
    val foregroundColor: String,
    val backgroundColor: String,
    val centerLogo: String,
    val selectFromGallery: String,
    val customLogoSelected: String,
    val removeCustomLogo: String,
    val shareQr: String,
    val downloadQr: String,
    val saveToHistory: String,
    val savedToHistory: String,
    val qrSavedSuccess: String,
    val shareChooserTitle: String,

    // Scan Screen
    val scanQrTitle: String,
    val cameraPermissionTitle: String,
    val cameraPermissionDesc: String,
    val grantPermission: String,
    val flashOn: String,
    val flashOff: String,
    val scanFromGallery: String,
    val cameraAimHint: String,
    val scannedResultTitle: String,
    val copyText: String,
    val copiedToClipboard: String,
    val openInBrowser: String,
    val openAction: String,
    val createSimilar: String,
    val close: String,
    val noQrFoundInImage: String,

    // History Screen
    val historyTitle: String,
    val historyScannedTab: String,
    val historyCreatedTab: String,
    val searchInHistory: String,
    val clearHistory: String,
    val clearHistoryConfirmTitle: String,
    val clearHistoryConfirmDesc: String,
    val yesClear: String,
    val cancel: String,
    val emptyScannedHistory: String,
    val emptyCreatedHistory: String,
    val recordDeleted: String,
    val historyCleared: String,

    // Preset Logo Names
    val logoNone: String,
    val logoWeb: String,
    val logoWifi: String,
    val logoPhone: String,
    val logoMail: String,
    val logoStar: String,
    val logoHeart: String,
    val logoShop: String,

    // Color Names
    val colorBlack: String,
    val colorNightBlue: String,
    val colorEmerald: String,
    val colorPurple: String,
    val colorCrimson: String,
    val colorDarkCyan: String,
    val colorWhite: String,
    val colorCream: String,
    val colorLightGray: String,
    val colorIceBlue: String,

    // About Screen
    val tabAbout: String = "About",
    val aboutTitle: String = "About",
    val appVersion: String = "v1.1.0",
    val checkUpdates: String = "Check for Updates",
    val checkingForUpdates: String = "Checking for updates...",
    val latestVersionInstalled: String = "You are using the latest version (v1.1.0)!",
    val updateNotificationsTitle: String = "Update Notifications",
    val updateNotificationsDesc: String = "Would you like to receive notifications when new updates or features are released?",
    val allowNotifications: String = "Allow",
    val notNow: String = "Not Now",
    val notificationsActive: String = "Update notifications are active",
    val notificationsOff: String = "Notifications disabled",
    val projectLicenseTitle: String = "Project License (MIT)",
    val projectLicenseSubtitle: String = "MIT License - dragons-fox0058",
    val thirdPartyLicensesTitle: String = "Third-Party Licenses",
    val thirdPartyLicensesSubtitle: String = "ZXing, CameraX, Room, Coil, Compose",
    val repositoryTitle: String = "GitHub Repository",
    val repositorySubtitle: String = "Dragons-Fox0058 / qr-code-studio",
    val changelogTitle: String = "Changelog",
    val changelogSubtitle: String = "v1.1.0 & v1.0.0 release notes",
    val releaseBadge: String = "Release",
    val currentVersionBadge: String = "Latest Version",
    val initialVersionBadge: String = "Initial Release",
    val designCredits: String = "Designed with Material Design 3 & Expressive Dynamic Color",
    val changelogV110List: List<String> = listOf(
        "Added About section with detailed app info",
        "Integrated GitHub repository (Dragons-Fox0058/qr-code-studio)",
        "Added update notification engine & first-run prompt",
        "Added MIT Project License & Third-Party library licenses",
        "Added interactive Changelog viewer",
        "Enabled Android 12+ Material You dynamic wallpaper theming"
    ),
    val changelogV100List: List<String> = listOf(
        "Customizable QR generator (URL, Text, Wi-Fi, Phone, Email, SMS)",
        "Real-time camera & gallery image QR scanner (CameraX & ZXing)",
        "Custom foreground/background colors and center logos",
        "Offline local SQLite Room database history",
        "20+ languages support with automatic system locale detection"
    )
)

object LanguageManager {

    fun getEffectiveLanguageCode(selectedCode: String): String {
        return if (selectedCode == AppLanguage.SYSTEM.code) {
            Locale.getDefault().language.lowercase()
        } else {
            selectedCode.lowercase()
        }
    }

    fun getStrings(selectedCode: String): TranslationStrings {
        val code = getEffectiveLanguageCode(selectedCode)
        return when (code) {
            "tr", "az" -> turkishStrings
            "es" -> spanishStrings
            "de" -> germanStrings
            "fr" -> frenchStrings
            "it" -> italianStrings
            "pt" -> portugueseStrings
            "ru", "uk" -> russianStrings
            "zh" -> chineseStrings
            "ja" -> japaneseStrings
            "ko" -> koreanStrings
            "ar" -> arabicStrings
            "hi" -> hindiStrings
            "nl" -> dutchStrings
            "pl" -> polishStrings
            "id" -> indonesianStrings
            "vi" -> vietnameseStrings
            else -> englishStrings // Default to universal English for all other languages
        }
    }

    private val turkishStrings = TranslationStrings(
        appTitle = "QR Kod Stüdyosu",
        tabCreate = "Oluştur",
        tabScan = "Tara",
        tabHistory = "Geçmiş",
        changeTheme = "Temayı Değiştir",
        changeLanguage = "Dil Seç",
        autoDetectLanguage = "Otomatik Algıla (Sistem)",
        selectLanguageTitle = "Uygulama Dilini Seçin",
        createQrTitle = "QR Kod Oluşturucu",
        qrTypeUrl = "Web Sitesi",
        qrTypeText = "Metin",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Telefon",
        qrTypeEmail = "E-posta",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Web Sitesi Bağlantısı (URL)",
        textContentLabel = "Metin İçeriği",
        wifiSsidLabel = "Ağ Adı (SSID)",
        wifiPasswordLabel = "Wi-Fi Şifresi",
        wifiSecurityLabel = "Güvenlik Türü",
        wifiNone = "Şifresiz",
        phoneNumberLabel = "Telefon Numarası",
        emailToLabel = "Alıcı E-posta",
        emailSubjectLabel = "Konu",
        emailBodyLabel = "Mesaj İçeriği",
        smsPhoneLabel = "Telefon Numarası",
        smsMessageLabel = "SMS Mesajı",
        appearanceAndLogo = "Görünüm & Logo",
        foregroundColor = "Ön Plan Rengi",
        backgroundColor = "Arka Plan Rengi",
        centerLogo = "Merkez Logo / Simge",
        selectFromGallery = "Galeriden Özel Logo Seç",
        customLogoSelected = "Özel Logo Seçildi",
        removeCustomLogo = "Kaldır",
        shareQr = "Paylaş",
        downloadQr = "İndir",
        saveToHistory = "Geçmişe Kaydet",
        savedToHistory = "QR Kod geçmişe kaydedildi.",
        qrSavedSuccess = "QR Kod Galeriye Kaydedildi!",
        shareChooserTitle = "QR Kodu Paylaş",
        scanQrTitle = "QR Kod Tara",
        cameraPermissionTitle = "Kamera İzni Gerekiyor",
        cameraPermissionDesc = "QR kodları gerçek zamanlı tarayabilmek için kamera erişimine izin vermelisiniz.",
        grantPermission = "İzin Ver",
        flashOn = "Flaş Açık",
        flashOff = "Flaş Kapalı",
        scanFromGallery = "Galeriden Seç",
        cameraAimHint = "QR kodu çerçevenin içine hizalayın",
        scannedResultTitle = "Taranan QR Kod",
        copyText = "Kopyala",
        copiedToClipboard = "Panoya kopyalandı",
        openInBrowser = "Tarayıcıda Aç",
        openAction = "Aç",
        createSimilar = "Benzerini Oluştur",
        close = "Kapat",
        noQrFoundInImage = "Seçilen görselde QR kod bulunamadı",
        historyTitle = "Geçmiş",
        historyScannedTab = "Tarananlar",
        historyCreatedTab = "Oluşturulanlar",
        searchInHistory = "Geçmişte ara...",
        clearHistory = "Geçmişi Temizle",
        clearHistoryConfirmTitle = "Geçmişi Temizle",
        clearHistoryConfirmDesc = "Bu sekmedeki tüm geçmiş kayıtlarını silmek istediğinize emin misiniz?",
        yesClear = "Evet, Temizle",
        cancel = "İptal",
        emptyScannedHistory = "Henüz taranmış bir QR kod yok",
        emptyCreatedHistory = "Henüz oluşturulmuş bir QR kod yok",
        recordDeleted = "Kayıt silindi.",
        historyCleared = "Geçmiş temizlendi.",
        logoNone = "Yok",
        logoWeb = "Web",
        logoWifi = "Wi-Fi",
        logoPhone = "Telefon",
        logoMail = "E-posta",
        logoStar = "Yıldız",
        logoHeart = "Kalp",
        logoShop = "Alışveriş",
        colorBlack = "Siyah",
        colorNightBlue = "Gece Mavisi",
        colorEmerald = "Zümrüt",
        colorPurple = "Mürdüm",
        colorCrimson = "Kızıl",
        colorDarkCyan = "Koyu Camgöbeği",
        colorWhite = "Beyaz",
        colorCream = "Krem",
        colorLightGray = "Açık Gri",
        colorIceBlue = "Buz Mavisi",
        tabAbout = "Hakkında",
        aboutTitle = "Hakkında",
        appVersion = "v1.1.0",
        checkUpdates = "Güncellemeleri Denetle",
        checkingForUpdates = "Güncellemeler denetleniyor...",
        latestVersionInstalled = "En güncel sürümü (v1.1.0) kullanıyorsunuz!",
        updateNotificationsTitle = "Güncelleme Bildirimleri",
        updateNotificationsDesc = "Uygulamaya yeni bir güncelleme veya özellik geldiğinde bildirim almak ister misiniz?",
        allowNotifications = "İzin Ver",
        notNow = "Şimdi Değil",
        notificationsActive = "Güncelleme bildirimleri aktif",
        notificationsOff = "Bildirimler kapalı",
        projectLicenseTitle = "Proje Lisansı (MIT)",
        projectLicenseSubtitle = "MIT Lisansı - dragons-fox0058",
        thirdPartyLicensesTitle = "Üçüncü Taraf Lisansları",
        thirdPartyLicensesSubtitle = "ZXing, CameraX, Room, Coil, Compose",
        repositoryTitle = "GitHub Deposu",
        repositorySubtitle = "Dragons-Fox0058 / qr-code-studio",
        changelogTitle = "Değişiklik Günlüğü",
        changelogSubtitle = "v1.1.0 ve v1.0.0 sürüm notları",
        releaseBadge = "Kararlı",
        currentVersionBadge = "Güncel Sürüm",
        initialVersionBadge = "İlk Sürüm",
        designCredits = "Material Design 3 ve Expressive Dinamik Renk ile tasarlandı",
        changelogV110List = listOf(
            "Hakkında sekmesi eklendi",
            "GitHub deposu (Dragons-Fox0058/qr-code-studio) entegre edildi",
            "Güncelleme bildirimleri sistemi ve ilk açılış izni eklendi",
            "Proje (MIT) ve Üçüncü Taraf lisansları eklendi",
            "Etkileşimli Değişiklik Günlüğü (Changelog) eklendi",
            "Android 12+ Material You dinamik duvar kağıdı teması aktif edildi"
        ),
        changelogV100List = listOf(
            "Özelleştirilebilir QR kod oluşturucu (URL, Metin, Wi-Fi, Telefon, E-posta, SMS)",
            "Canlı kamera ve galeriden görsel tarama (CameraX & ZXing)",
            "Özel renkler ve merkez logo desteği",
            "Yerel SQLite Room veritabanı ile geçmiş kaydı",
            "20+ dil desteği ve otomatik sistem dili algılama"
        )
    )

    private val englishStrings = TranslationStrings(
        appTitle = "QR Code Studio",
        tabCreate = "Create",
        tabScan = "Scan",
        tabHistory = "History",
        changeTheme = "Change Theme",
        changeLanguage = "Select Language",
        autoDetectLanguage = "Auto Detect (System)",
        selectLanguageTitle = "Choose App Language",
        createQrTitle = "QR Code Generator",
        qrTypeUrl = "Website",
        qrTypeText = "Text",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Phone",
        qrTypeEmail = "Email",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Website Link (URL)",
        textContentLabel = "Text Content",
        wifiSsidLabel = "Network Name (SSID)",
        wifiPasswordLabel = "Wi-Fi Password",
        wifiSecurityLabel = "Security Type",
        wifiNone = "Open (None)",
        phoneNumberLabel = "Phone Number",
        emailToLabel = "Recipient Email",
        emailSubjectLabel = "Subject",
        emailBodyLabel = "Message Content",
        smsPhoneLabel = "Phone Number",
        smsMessageLabel = "SMS Message",
        appearanceAndLogo = "Appearance & Logo",
        foregroundColor = "Foreground Color",
        backgroundColor = "Background Color",
        centerLogo = "Center Logo / Icon",
        selectFromGallery = "Select Custom Logo from Gallery",
        customLogoSelected = "Custom Logo Selected",
        removeCustomLogo = "Remove",
        shareQr = "Share",
        downloadQr = "Download",
        saveToHistory = "Save to History",
        savedToHistory = "QR Code saved to history.",
        qrSavedSuccess = "QR Code Saved to Gallery!",
        shareChooserTitle = "Share QR Code",
        scanQrTitle = "Scan QR Code",
        cameraPermissionTitle = "Camera Permission Required",
        cameraPermissionDesc = "Please grant camera permission to scan QR codes in real time.",
        grantPermission = "Grant Permission",
        flashOn = "Flash On",
        flashOff = "Flash Off",
        scanFromGallery = "Choose from Gallery",
        cameraAimHint = "Align QR code within the frame",
        scannedResultTitle = "Scanned QR Code",
        copyText = "Copy",
        copiedToClipboard = "Copied to clipboard",
        openInBrowser = "Open in Browser",
        openAction = "Open",
        createSimilar = "Create Similar",
        close = "Close",
        noQrFoundInImage = "No QR code found in selected image",
        historyTitle = "History",
        historyScannedTab = "Scanned",
        historyCreatedTab = "Created",
        searchInHistory = "Search history...",
        clearHistory = "Clear History",
        clearHistoryConfirmTitle = "Clear History",
        clearHistoryConfirmDesc = "Are you sure you want to delete all records in this tab?",
        yesClear = "Yes, Clear",
        cancel = "Cancel",
        emptyScannedHistory = "No scanned QR codes yet",
        emptyCreatedHistory = "No created QR codes yet",
        recordDeleted = "Record deleted.",
        historyCleared = "History cleared.",
        logoNone = "None",
        logoWeb = "Web",
        logoWifi = "Wi-Fi",
        logoPhone = "Phone",
        logoMail = "Email",
        logoStar = "Star",
        logoHeart = "Heart",
        logoShop = "Shopping",
        colorBlack = "Black",
        colorNightBlue = "Night Blue",
        colorEmerald = "Emerald",
        colorPurple = "Purple",
        colorCrimson = "Crimson",
        colorDarkCyan = "Dark Cyan",
        colorWhite = "White",
        colorCream = "Cream",
        colorLightGray = "Light Gray",
        colorIceBlue = "Ice Blue"
    )

    private val spanishStrings = englishStrings.copy(
        appTitle = "Estudio Código QR",
        tabCreate = "Crear",
        tabScan = "Escanear",
        tabHistory = "Historial",
        changeTheme = "Cambiar tema",
        changeLanguage = "Seleccionar idioma",
        autoDetectLanguage = "Detección automática (Sistema)",
        selectLanguageTitle = "Seleccionar idioma de la app",
        createQrTitle = "Generador de Código QR",
        qrTypeUrl = "Sitio Web",
        qrTypeText = "Texto",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Teléfono",
        qrTypeEmail = "Correo",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Enlace Web (URL)",
        textContentLabel = "Contenido de texto",
        wifiSsidLabel = "Nombre de red (SSID)",
        wifiPasswordLabel = "Contraseña Wi-Fi",
        wifiSecurityLabel = "Seguridad",
        wifiNone = "Sin contraseña",
        phoneNumberLabel = "Número de teléfono",
        emailToLabel = "Correo de destino",
        emailSubjectLabel = "Asunto",
        emailBodyLabel = "Mensaje",
        smsPhoneLabel = "Número de teléfono",
        smsMessageLabel = "Mensaje SMS",
        appearanceAndLogo = "Aspecto y Logotipo",
        foregroundColor = "Color de primer plano",
        backgroundColor = "Color de fondo",
        centerLogo = "Logo / Icono central",
        selectFromGallery = "Elegir logo de la galería",
        customLogoSelected = "Logo personalizado seleccionado",
        removeCustomLogo = "Quitar",
        shareQr = "Compartir",
        downloadQr = "Descargar",
        saveToHistory = "Guardar en historial",
        savedToHistory = "Código QR guardado en el historial.",
        qrSavedSuccess = "¡Código QR guardado en la galería!",
        shareChooserTitle = "Compartir Código QR",
        scanQrTitle = "Escanear Código QR",
        cameraPermissionTitle = "Permiso de cámara requerido",
        cameraPermissionDesc = "Permita el acceso a la cámara para escanear códigos QR en tiempo real.",
        grantPermission = "Conceder permiso",
        flashOn = "Flash encendido",
        flashOff = "Flash apagado",
        scanFromGallery = "Elegir de la galería",
        cameraAimHint = "Alinee el código QR dentro del marco",
        scannedResultTitle = "Código QR escaneado",
        copyText = "Copiar",
        copiedToClipboard = "Copiado al portapapeles",
        openInBrowser = "Abrir en navegador",
        openAction = "Abrir",
        createSimilar = "Crear similar",
        close = "Cerrar",
        noQrFoundInImage = "No se encontró ningún código QR en la imagen",
        historyTitle = "Historial",
        historyScannedTab = "Escaneados",
        historyCreatedTab = "Creados",
        searchInHistory = "Buscar en el historial...",
        clearHistory = "Borrar historial",
        clearHistoryConfirmTitle = "Borrar historial",
        clearHistoryConfirmDesc = "¿Seguro que desea eliminar todos los registros de esta pestaña?",
        yesClear = "Sí, borrar",
        cancel = "Cancelar",
        emptyScannedHistory = "Aún no hay códigos escaneados",
        emptyCreatedHistory = "Aún no hay códigos creados",
        recordDeleted = "Registro eliminado.",
        historyCleared = "Historial borrado.",
        tabAbout = "Acerca de",
        aboutTitle = "Acerca de",
        checkUpdates = "Buscar actualizaciones",
        repositoryTitle = "Repositorio GitHub",
        projectLicenseTitle = "Licencia del proyecto (MIT)",
        thirdPartyLicensesTitle = "Licencias de terceros",
        changelogTitle = "Registro de cambios",
        releaseBadge = "Estable",
        currentVersionBadge = "Versión actual",
        initialVersionBadge = "Versión inicial"
    )

    private val germanStrings = englishStrings.copy(
        appTitle = "QR-Code Studio",
        tabCreate = "Erstellen",
        tabScan = "Scannen",
        tabHistory = "Verlauf",
        changeTheme = "Design ändern",
        changeLanguage = "Sprache wählen",
        autoDetectLanguage = "Automatisch erkennen (System)",
        selectLanguageTitle = "App-Sprache wählen",
        createQrTitle = "QR-Code-Generator",
        qrTypeUrl = "Webseite",
        qrTypeText = "Text",
        qrTypeWifi = "WLAN",
        qrTypePhone = "Telefon",
        qrTypeEmail = "E-Mail",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Webseiten-Link (URL)",
        textContentLabel = "Textinhalt",
        wifiSsidLabel = "Netzwerkname (SSID)",
        wifiPasswordLabel = "WLAN-Passwort",
        wifiSecurityLabel = "Sicherheitstyp",
        wifiNone = "Keine (Offen)",
        phoneNumberLabel = "Telefonnummer",
        emailToLabel = "Empfänger E-Mail",
        emailSubjectLabel = "Betreff",
        emailBodyLabel = "Nachricht",
        smsPhoneLabel = "Telefonnummer",
        smsMessageLabel = "SMS-Nachricht",
        appearanceAndLogo = "Aussehen & Logo",
        foregroundColor = "Vordergrundfarbe",
        backgroundColor = "Hintergrundfarbe",
        centerLogo = "Mittiges Logo / Icon",
        selectFromGallery = "Eigenes Logo aus Galerie wählen",
        customLogoSelected = "Eigenes Logo ausgewählt",
        removeCustomLogo = "Entfernen",
        shareQr = "Teilen",
        downloadQr = "Herunterladen",
        saveToHistory = "Im Verlauf speichern",
        savedToHistory = "QR-Code im Verlauf gespeichert.",
        qrSavedSuccess = "QR-Code in Galerie gespeichert!",
        shareChooserTitle = "QR-Code teilen",
        scanQrTitle = "QR-Code scannen",
        cameraPermissionTitle = "Kameraberechtigung erforderlich",
        cameraPermissionDesc = "Bitte Kameraberechtigung erteilen, um QR-Codes live zu scannen.",
        grantPermission = "Berechtigung erteilen",
        flashOn = "Blitz an",
        flashOff = "Blitz aus",
        scanFromGallery = "Aus Galerie wählen",
        cameraAimHint = "QR-Code im Rahmen ausrichten",
        scannedResultTitle = "Gescannter QR-Code",
        copyText = "Kopieren",
        copiedToClipboard = "In Zwischenablage kopiert",
        openInBrowser = "Im Browser öffnen",
        openAction = "Öffnen",
        createSimilar = "Ähnlichen erstellen",
        close = "Schließen",
        noQrFoundInImage = "Kein QR-Code im Bild gefunden",
        historyTitle = "Verlauf",
        historyScannedTab = "Gescannte",
        historyCreatedTab = "Erstellte",
        searchInHistory = "Im Verlauf suchen...",
        clearHistory = "Verlauf leeren",
        clearHistoryConfirmTitle = "Verlauf leeren",
        clearHistoryConfirmDesc = "Möchten Sie wirklich alle Einträge in diesem Tab löschen?",
        yesClear = "Ja, leeren",
        cancel = "Abbrechen",
        emptyScannedHistory = "Noch keine gescannten QR-Codes",
        emptyCreatedHistory = "Noch keine erstellten QR-Codes",
        recordDeleted = "Eintrag gelöscht.",
        historyCleared = "Verlauf geleert.",
        tabAbout = "Über",
        aboutTitle = "Über",
        checkUpdates = "Nach Updates suchen",
        repositoryTitle = "GitHub-Repository",
        projectLicenseTitle = "Projektlizenz (MIT)",
        thirdPartyLicensesTitle = "Drittanbieter-Lizenzen",
        changelogTitle = "Änderungsprotokoll",
        releaseBadge = "Stabil",
        currentVersionBadge = "Aktuelle Version",
        initialVersionBadge = "Erstversion"
    )

    private val frenchStrings = englishStrings.copy(
        appTitle = "Studio Code QR",
        tabCreate = "Créer",
        tabScan = "Scanner",
        tabHistory = "Historique",
        changeTheme = "Changer de thème",
        changeLanguage = "Choisir la langue",
        autoDetectLanguage = "Détection automatique (Système)",
        selectLanguageTitle = "Choisir la langue de l'application",
        createQrTitle = "Générateur de Code QR",
        qrTypeUrl = "Site Web",
        qrTypeText = "Texte",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Téléphone",
        qrTypeEmail = "E-mail",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Lien du site (URL)",
        textContentLabel = "Contenu textuel",
        wifiSsidLabel = "Nom du réseau (SSID)",
        wifiPasswordLabel = "Mot de passe Wi-Fi",
        wifiSecurityLabel = "Sécurité",
        wifiNone = "Sans mot de passe",
        phoneNumberLabel = "Numéro de téléphone",
        emailToLabel = "E-mail du destinataire",
        emailSubjectLabel = "Objet",
        emailBodyLabel = "Message",
        smsPhoneLabel = "Numéro de téléphone",
        smsMessageLabel = "Message SMS",
        appearanceAndLogo = "Apparence & Logo",
        foregroundColor = "Couleur principale",
        backgroundColor = "Couleur d'arrière-plan",
        centerLogo = "Logo / Icône au centre",
        selectFromGallery = "Choisir un logo dans la galerie",
        customLogoSelected = "Logo personnalisé sélectionné",
        removeCustomLogo = "Supprimer",
        shareQr = "Partager",
        downloadQr = "Télécharger",
        saveToHistory = "Enregistrer dans l'historique",
        savedToHistory = "Code QR enregistré dans l'historique.",
        qrSavedSuccess = "Code QR enregistré dans la galerie !",
        shareChooserTitle = "Partager le code QR",
        scanQrTitle = "Scanner un code QR",
        cameraPermissionTitle = "Autorisation de caméra requise",
        cameraPermissionDesc = "Veuillez autoriser l'accès à la caméra pour scanner les codes QR en direct.",
        grantPermission = "Autoriser",
        flashOn = "Flash allumé",
        flashOff = "Flash éteint",
        scanFromGallery = "Choisir depuis la galerie",
        cameraAimHint = "Alignez le code QR dans le cadre",
        scannedResultTitle = "Code QR scanné",
        copyText = "Copier",
        copiedToClipboard = "Copié dans le presse-papier",
        openInBrowser = "Ouvrir dans le navigateur",
        openAction = "Ouvrir",
        createSimilar = "Créer similaire",
        close = "Fermer",
        noQrFoundInImage = "Aucun code QR trouvé dans l'image",
        historyTitle = "Historique",
        historyScannedTab = "Scannés",
        historyCreatedTab = "Créés",
        searchInHistory = "Rechercher dans l'historique...",
        clearHistory = "Effacer l'historique",
        clearHistoryConfirmTitle = "Effacer l'historique",
        clearHistoryConfirmDesc = "Voulez-vous vraiment effacer tous les éléments de cet onglet ?",
        yesClear = "Oui, effacer",
        cancel = "Annuler",
        emptyScannedHistory = "Aucun code QR scanné pour l'instant",
        emptyCreatedHistory = "Aucun code QR créé pour l'instant",
        recordDeleted = "Élément supprimé.",
        historyCleared = "Historique effacé.",
        tabAbout = "À propos",
        aboutTitle = "À propos",
        checkUpdates = "Vérifier les mises à jour",
        repositoryTitle = "Dépôt GitHub",
        projectLicenseTitle = "Licence du projet (MIT)",
        thirdPartyLicensesTitle = "Licences tierces",
        changelogTitle = "Journal des modifications",
        releaseBadge = "Stable",
        currentVersionBadge = "Version actuelle",
        initialVersionBadge = "Version initiale"
    )

    private val italianStrings = englishStrings.copy(
        appTitle = "Studio Codici QR",
        tabCreate = "Crea",
        tabScan = "Scansiona",
        tabHistory = "Cronologia",
        changeTheme = "Cambia tema",
        changeLanguage = "Seleziona lingua",
        autoDetectLanguage = "Rilevamento automatico (Sistema)",
        selectLanguageTitle = "Scegli la lingua dell'app",
        createQrTitle = "Generatore di Codici QR",
        qrTypeUrl = "Sito Web",
        qrTypeText = "Testo",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Telefono",
        qrTypeEmail = "Email",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Link sito Web (URL)",
        textContentLabel = "Contenuto del testo",
        wifiSsidLabel = "Nome della rete (SSID)",
        wifiPasswordLabel = "Password Wi-Fi",
        wifiSecurityLabel = "Sicurezza",
        wifiNone = "Aperta (Nessuna)",
        phoneNumberLabel = "Numero di telefono",
        emailToLabel = "Email destinatario",
        emailSubjectLabel = "Oggetto",
        emailBodyLabel = "Messaggio",
        smsPhoneLabel = "Numero di telefono",
        smsMessageLabel = "Messaggio SMS",
        appearanceAndLogo = "Aspetto e Logo",
        foregroundColor = "Colore in primo piano",
        backgroundColor = "Colore di sfondo",
        centerLogo = "Logo / Icona centrale",
        selectFromGallery = "Scegli logo dalla galleria",
        customLogoSelected = "Logo personalizzato selezionato",
        removeCustomLogo = "Rimuovi",
        shareQr = "Condividi",
        downloadQr = "Scarica",
        saveToHistory = "Salva nella cronologia",
        savedToHistory = "Codice QR salvato nella cronologia.",
        qrSavedSuccess = "Codice QR salvato nella galleria!",
        shareChooserTitle = "Condividi codice QR",
        scanQrTitle = "Scansiona codice QR",
        cameraPermissionTitle = "Autorizzazione fotocamera richiesta",
        cameraPermissionDesc = "Autorizza l'accesso alla fotocamera per scansionare i codici QR in tempo reale.",
        grantPermission = "Consenti",
        flashOn = "Flash attivo",
        flashOff = "Flash spento",
        scanFromGallery = "Scegli dalla galleria",
        cameraAimHint = "Inquadra il codice QR nella cornice",
        scannedResultTitle = "Codice QR scansionato",
        copyText = "Copia",
        copiedToClipboard = "Copiato negli appunti",
        openInBrowser = "Apri nel browser",
        openAction = "Apri",
        createSimilar = "Crea simile",
        close = "Chiudi",
        noQrFoundInImage = "Nessun codice QR trovato nell'immagine",
        historyTitle = "Cronologia",
        historyScannedTab = "Scansionati",
        historyCreatedTab = "Creati",
        searchInHistory = "Cerca nella cronologia...",
        clearHistory = "Cancella cronologia",
        clearHistoryConfirmTitle = "Cancella cronologia",
        clearHistoryConfirmDesc = "Sei sicuro di voler eliminare tutti i dati di questa scheda?",
        yesClear = "Sì, cancella",
        cancel = "Annulla",
        emptyScannedHistory = "Nessun codice QR scansionato",
        emptyCreatedHistory = "Nessun codice QR creato",
        recordDeleted = "Elemento eliminato.",
        historyCleared = "Cronologia cancellata."
    )

    private val portugueseStrings = englishStrings.copy(
        appTitle = "Estúdio Código QR",
        tabCreate = "Criar",
        tabScan = "Escanear",
        tabHistory = "Histórico",
        changeTheme = "Alterar tema",
        changeLanguage = "Selecionar idioma",
        autoDetectLanguage = "Detecção automática (Sistema)",
        selectLanguageTitle = "Escolher idioma do aplicativo",
        createQrTitle = "Gerador de Código QR",
        qrTypeUrl = "Site",
        qrTypeText = "Texto",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Telefone",
        qrTypeEmail = "E-mail",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Link do site (URL)",
        textContentLabel = "Conteúdo de texto",
        wifiSsidLabel = "Nome da rede (SSID)",
        wifiPasswordLabel = "Senha do Wi-Fi",
        wifiSecurityLabel = "Segurança",
        wifiNone = "Sem senha",
        phoneNumberLabel = "Número de telefone",
        emailToLabel = "E-mail de destino",
        emailSubjectLabel = "Assunto",
        emailBodyLabel = "Mensagem",
        smsPhoneLabel = "Número de telefone",
        smsMessageLabel = "Mensagem SMS",
        appearanceAndLogo = "Aparência e Logo",
        foregroundColor = "Cor principal",
        backgroundColor = "Cor de fundo",
        centerLogo = "Logo / Ícone central",
        selectFromGallery = "Escolher logo da galeria",
        customLogoSelected = "Logo personalizado selecionado",
        removeCustomLogo = "Remover",
        shareQr = "Compartilhar",
        downloadQr = "Baixar",
        saveToHistory = "Salvar no histórico",
        savedToHistory = "Código QR salvo no histórico.",
        qrSavedSuccess = "Código QR salvo na galeria!",
        shareChooserTitle = "Compartilhar código QR",
        scanQrTitle = "Escanear Código QR",
        cameraPermissionTitle = "Permissão de câmera necessária",
        cameraPermissionDesc = "Permita o acesso à câmera para escanear códigos QR em tempo real.",
        grantPermission = "Permitir",
        flashOn = "Flash ligado",
        flashOff = "Flash desligado",
        scanFromGallery = "Escolher da galeria",
        cameraAimHint = "Alinhe o código QR dentro do quadro",
        scannedResultTitle = "Código QR escaneado",
        copyText = "Copiar",
        copiedToClipboard = "Copiado para a área de transferência",
        openInBrowser = "Abrir no navegador",
        openAction = "Abrir",
        createSimilar = "Criar similar",
        close = "Fechar",
        noQrFoundInImage = "Nenhum código QR encontrado na imagem",
        historyTitle = "Histórico",
        historyScannedTab = "Escaneados",
        historyCreatedTab = "Criados",
        searchInHistory = "Pesquisar no histórico...",
        clearHistory = "Limpar histórico",
        clearHistoryConfirmTitle = "Limpar histórico",
        clearHistoryConfirmDesc = "Tem certeza de que deseja excluir todos os registros desta aba?",
        yesClear = "Sim, limpar",
        cancel = "Cancelar",
        emptyScannedHistory = "Nenhum código QR escaneado ainda",
        emptyCreatedHistory = "Nenhum código QR criado ainda",
        recordDeleted = "Registro excluído.",
        historyCleared = "Histórico limpo.",
        tabAbout = "Sobre",
        aboutTitle = "Sobre",
        checkUpdates = "Verificar atualizações",
        repositoryTitle = "Repositório GitHub",
        projectLicenseTitle = "Licença do Projeto (MIT)",
        thirdPartyLicensesTitle = "Licenças de Terceiros",
        changelogTitle = "Registro de Alterações",
        releaseBadge = "Estável",
        currentVersionBadge = "Versão Atual",
        initialVersionBadge = "Versão Inicial"
    )

    private val russianStrings = englishStrings.copy(
        appTitle = "QR Студия",
        tabCreate = "Создать",
        tabScan = "Сканировать",
        tabHistory = "История",
        changeTheme = "Сменить тему",
        changeLanguage = "Выбрать язык",
        autoDetectLanguage = "Автоопределение (Система)",
        selectLanguageTitle = "Выберите язык приложения",
        createQrTitle = "Генератор QR-кодов",
        qrTypeUrl = "Веб-сайт",
        qrTypeText = "Текст",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Телефон",
        qrTypeEmail = "Эл. почта",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Ссылка на сайт (URL)",
        textContentLabel = "Текстовое содержимое",
        wifiSsidLabel = "Имя сети (SSID)",
        wifiPasswordLabel = "Пароль Wi-Fi",
        wifiSecurityLabel = "Тип безопасности",
        wifiNone = "Без пароля",
        phoneNumberLabel = "Номер телефона",
        emailToLabel = "Кому (Email)",
        emailSubjectLabel = "Тема",
        emailBodyLabel = "Текст сообщения",
        smsPhoneLabel = "Номер телефона",
        smsMessageLabel = "Текст SMS",
        appearanceAndLogo = "Оформление и логотип",
        foregroundColor = "Цвет кода",
        backgroundColor = "Цвет фона",
        centerLogo = "Центральный логотип / иконка",
        selectFromGallery = "Выбрать логотип из галереи",
        customLogoSelected = "Свой логотип выбран",
        removeCustomLogo = "Удалить",
        shareQr = "Поделиться",
        downloadQr = "Скачать",
        saveToHistory = "Сохранить в историю",
        savedToHistory = "QR-код сохранен в истории.",
        qrSavedSuccess = "QR-код сохранен в галерею!",
        shareChooserTitle = "Поделиться QR-кодом",
        scanQrTitle = "Сканировать QR-код",
        cameraPermissionTitle = "Требуется доступ к камере",
        cameraPermissionDesc = "Предоставьте доступ к камере для сканирования QR-кодов в реальном времени.",
        grantPermission = "Разрешить",
        flashOn = "Фонарик вкл",
        flashOff = "Фонарик выкл",
        scanFromGallery = "Выбрать из галереи",
        cameraAimHint = "Поместите QR-код в рамку",
        scannedResultTitle = "Отсканированный QR-код",
        copyText = "Копировать",
        copiedToClipboard = "Скопировано в буфер обмена",
        openInBrowser = "Открыть в браузере",
        openAction = "Открыть",
        createSimilar = "Создать похожий",
        close = "Закрыть",
        noQrFoundInImage = "QR-код на изображении не найден",
        historyTitle = "История",
        historyScannedTab = "Отсканированные",
        historyCreatedTab = "Созданные",
        searchInHistory = "Поиск по истории...",
        clearHistory = "Очистить историю",
        clearHistoryConfirmTitle = "Очистить историю",
        clearHistoryConfirmDesc = "Вы уверены, что хотите удалить все записи в этой вкладке?",
        yesClear = "Да, очистить",
        cancel = "Отмена",
        emptyScannedHistory = "Пока нет отсканированных QR-кодов",
        emptyCreatedHistory = "Пока нет созданных QR-кодов",
        recordDeleted = "Запись удалена.",
        historyCleared = "История очищена.",
        tabAbout = "О приложении",
        aboutTitle = "О приложении",
        checkUpdates = "Проверить обновления",
        repositoryTitle = "Репозиторий GitHub",
        projectLicenseTitle = "Лицензия проекта (MIT)",
        thirdPartyLicensesTitle = "Сторонние лицензии",
        changelogTitle = "Список изменений",
        releaseBadge = "Стабильная",
        currentVersionBadge = "Текущая версия",
        initialVersionBadge = "Первый релиз"
    )

    private val chineseStrings = englishStrings.copy(
        appTitle = "QR 码工作室",
        tabCreate = "生成",
        tabScan = "扫描",
        tabHistory = "历史",
        changeTheme = "切换主题",
        changeLanguage = "选择语言",
        autoDetectLanguage = "自动检测 (系统默认)",
        selectLanguageTitle = "选择应用语言",
        createQrTitle = "二维码生成器",
        qrTypeUrl = "网站",
        qrTypeText = "文本",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "电话",
        qrTypeEmail = "电子邮件",
        qrTypeSms = "短信",
        websiteUrlLabel = "网站链接 (URL)",
        textContentLabel = "文本内容",
        wifiSsidLabel = "网络名称 (SSID)",
        wifiPasswordLabel = "Wi-Fi 密码",
        wifiSecurityLabel = "加密类型",
        wifiNone = "无密码",
        phoneNumberLabel = "电话号码",
        emailToLabel = "收件人邮箱",
        emailSubjectLabel = "主题",
        emailBodyLabel = "邮件内容",
        smsPhoneLabel = "电话号码",
        smsMessageLabel = "短信内容",
        appearanceAndLogo = "样式与徽标",
        foregroundColor = "前景色",
        backgroundColor = "背景色",
        centerLogo = "中心图标 / 徽标",
        selectFromGallery = "从相册选择自定义图标",
        customLogoSelected = "已选择自定义图标",
        removeCustomLogo = "移除",
        shareQr = "分享",
        downloadQr = "下载保存",
        saveToHistory = "保存到历史",
        savedToHistory = "二维码已保存至历史记录。",
        qrSavedSuccess = "二维码已成功保存到相册！",
        shareChooserTitle = "分享二维码",
        scanQrTitle = "扫描二维码",
        cameraPermissionTitle = "需要相机权限",
        cameraPermissionDesc = "请授予相机访问权限以实时扫描二维码。",
        grantPermission = "授予权限",
        flashOn = "开启手电筒",
        flashOff = "关闭手电筒",
        scanFromGallery = "从相册扫描",
        cameraAimHint = "将二维码对准取景框",
        scannedResultTitle = "扫描到的二维码",
        copyText = "复制",
        copiedToClipboard = "已复制到剪贴板",
        openInBrowser = "在浏览器中打开",
        openAction = "打开",
        createSimilar = "以此创建",
        close = "关闭",
        noQrFoundInImage = "所选图片中未检测到二维码",
        historyTitle = "历史记录",
        historyScannedTab = "扫描历史",
        historyCreatedTab = "生成历史",
        searchInHistory = "搜索历史...",
        clearHistory = "清空历史",
        clearHistoryConfirmTitle = "清空历史",
        clearHistoryConfirmDesc = "确定要删除此选项卡下的所有记录吗？",
        yesClear = "确定清空",
        cancel = "取消",
        emptyScannedHistory = "暂无扫描记录",
        emptyCreatedHistory = "暂无生成记录",
        recordDeleted = "记录已删除。",
        historyCleared = "历史记录已清空。"
    )

    private val japaneseStrings = englishStrings.copy(
        appTitle = "QRコードスタジオ",
        tabCreate = "作成",
        tabScan = "読み取り",
        tabHistory = "履歴",
        changeTheme = "テーマ切り替え",
        changeLanguage = "言語選択",
        autoDetectLanguage = "自動検出 (システム標準)",
        selectLanguageTitle = "アプリの言語を選択",
        createQrTitle = "QRコード作成",
        qrTypeUrl = "Webサイト",
        qrTypeText = "テキスト",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "電話",
        qrTypeEmail = "メール",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Webサイトリンク (URL)",
        textContentLabel = "テキスト内容",
        wifiSsidLabel = "ネットワーク名 (SSID)",
        wifiPasswordLabel = "Wi-Fiパスワード",
        wifiSecurityLabel = "セキュリティ",
        wifiNone = "パスワードなし",
        phoneNumberLabel = "電話番号",
        emailToLabel = "送信先メール",
        emailSubjectLabel = "件名",
        emailBodyLabel = "メッセージ本文",
        smsPhoneLabel = "電話番号",
        smsMessageLabel = "SMS本文",
        appearanceAndLogo = "デザインとロゴ",
        foregroundColor = "コードの色",
        backgroundColor = "背景色",
        centerLogo = "中央のロゴ / アイコン",
        selectFromGallery = "アルバムからロゴを選択",
        customLogoSelected = "カスタムロゴ選択済み",
        removeCustomLogo = "削除",
        shareQr = "共有",
        downloadQr = "保存",
        saveToHistory = "履歴に保存",
        savedToHistory = "QRコードを履歴に保存しました。",
        qrSavedSuccess = "QRコードをアルバムに保存しました！",
        shareChooserTitle = "QRコードを共有",
        scanQrTitle = "QRコードスキャン",
        cameraPermissionTitle = "カメラのアクセス権が必要です",
        cameraPermissionDesc = "QRコードをリアルタイムで読み取るにはカメラの許可が必要です。",
        grantPermission = "許可する",
        flashOn = "ライトON",
        flashOff = "ライトOFF",
        scanFromGallery = "写真から読み取る",
        cameraAimHint = "枠内にQRコードを合わせてください",
        scannedResultTitle = "スキャン結果",
        copyText = "コピー",
        copiedToClipboard = "クリップボードにコピーしました",
        openInBrowser = "ブラウザで開く",
        openAction = "開く",
        createSimilar = "同様のQRを作成",
        close = "閉じる",
        noQrFoundInImage = "画像からQRコードが見つかりませんでした",
        historyTitle = "履歴",
        historyScannedTab = "スキャン履歴",
        historyCreatedTab = "作成履歴",
        searchInHistory = "履歴を検索...",
        clearHistory = "履歴を消去",
        clearHistoryConfirmTitle = "履歴の消去",
        clearHistoryConfirmDesc = "このタブのすべての履歴を削除しますか？",
        yesClear = "消去する",
        cancel = "キャンセル",
        emptyScannedHistory = "スキャン履歴がありません",
        emptyCreatedHistory = "作成履歴がありません",
        recordDeleted = "削除しました。",
        historyCleared = "履歴を消去しました。"
    )

    private val koreanStrings = englishStrings.copy(
        appTitle = "QR 코드 스튜디오",
        tabCreate = "생성",
        tabScan = "스캔",
        tabHistory = "기록",
        changeTheme = "테마 변경",
        changeLanguage = "언어 선택",
        autoDetectLanguage = "자동 감지 (시스템 기본)",
        selectLanguageTitle = "앱 언어 선택",
        createQrTitle = "QR 코드 생성기",
        qrTypeUrl = "웹사이트",
        qrTypeText = "텍스트",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "전화번호",
        qrTypeEmail = "이메일",
        qrTypeSms = "SMS",
        websiteUrlLabel = "웹사이트 링크 (URL)",
        textContentLabel = "텍스트 내용",
        wifiSsidLabel = "네트워크 이름 (SSID)",
        wifiPasswordLabel = "Wi-Fi 비밀번호",
        wifiSecurityLabel = "보안 유형",
        wifiNone = "비밀번호 없음",
        phoneNumberLabel = "전화번호",
        emailToLabel = "받는 사람 이메일",
        emailSubjectLabel = "제목",
        emailBodyLabel = "메시지 내용",
        smsPhoneLabel = "전화번호",
        smsMessageLabel = "SMS 메시지",
        appearanceAndLogo = "디자인 및 로고",
        foregroundColor = "전경 색상",
        backgroundColor = "배경 색상",
        centerLogo = "중앙 로고 / 아이콘",
        selectFromGallery = "갤러리에서 로고 선택",
        customLogoSelected = "사용자 정의 로고 선택됨",
        removeCustomLogo = "제거",
        shareQr = "공유",
        downloadQr = "다운로드",
        saveToHistory = "기록에 저장",
        savedToHistory = "QR 코드가 기록에 저장되었습니다.",
        qrSavedSuccess = "QR 코드가 갤러리에 저장되었습니다!",
        shareChooserTitle = "QR 코드 공유",
        scanQrTitle = "QR 코드 스캔",
        cameraPermissionTitle = "카메라 권한 필요",
        cameraPermissionDesc = "실시간으로 QR 코드를 스캔하려면 카메라 권한을 허용해야 합니다.",
        grantPermission = "권한 허용",
        flashOn = "플래시 켜기",
        flashOff = "플래시 끄기",
        scanFromGallery = "갤러리에서 스캔",
        cameraAimHint = "프레임 안에 QR 코드를 맞춰주세요",
        scannedResultTitle = "스캔된 QR 코드",
        copyText = "복사",
        copiedToClipboard = "클립보드에 복사되었습니다",
        openInBrowser = "브라우저에서 열기",
        openAction = "열기",
        createSimilar = "유사하게 생성",
        close = "닫기",
        noQrFoundInImage = "선택한 이미지에서 QR 코드를 찾을 수 없습니다",
        historyTitle = "기록",
        historyScannedTab = "스캔 목록",
        historyCreatedTab = "생성 목록",
        searchInHistory = "기록 검색...",
        clearHistory = "기록 삭제",
        clearHistoryConfirmTitle = "기록 삭제",
        clearHistoryConfirmDesc = "이 탭의 모든 기록을 삭제하시겠습니까?",
        yesClear = "삭제",
        cancel = "취소",
        emptyScannedHistory = "아직 스캔된 QR 코드가 없습니다",
        emptyCreatedHistory = "아직 생성된 QR 코드가 없습니다",
        recordDeleted = "기록이 삭제되었습니다.",
        historyCleared = "기록이 모두 삭제되었습니다."
    )

    private val arabicStrings = englishStrings.copy(
        appTitle = "استوديو رمز الاستجابة السريعة",
        tabCreate = "إنشاء",
        tabScan = "مسح",
        tabHistory = "السجل",
        changeTheme = "تغيير المظهر",
        changeLanguage = "اختيار اللغة",
        autoDetectLanguage = "كشف تلقائي (لغة النظام)",
        selectLanguageTitle = "اختر لغة التطبيق",
        createQrTitle = "منشئ رمز QR",
        qrTypeUrl = "موقع إلكتروني",
        qrTypeText = "نص",
        qrTypeWifi = "واي فاي",
        qrTypePhone = "هاتف",
        qrTypeEmail = "بريد إلكتروني",
        qrTypeSms = "رسالة قصيرة",
        websiteUrlLabel = "رابط الموقع (URL)",
        textContentLabel = "محتوى النص",
        wifiSsidLabel = "اسم الشبكة (SSID)",
        wifiPasswordLabel = "كلمة مرور الواي فاي",
        wifiSecurityLabel = "نوع الأمان",
        wifiNone = "بدون كلمة مرور",
        phoneNumberLabel = "رقم الهاتف",
        emailToLabel = "البريد الإلكتروني للمستلم",
        emailSubjectLabel = "الموضوع",
        emailBodyLabel = "نص الرسالة",
        smsPhoneLabel = "رقم الهاتف",
        smsMessageLabel = "نص الرسالة القصيرة",
        appearanceAndLogo = "المظهر والشعار",
        foregroundColor = "لون الرمز",
        backgroundColor = "لون الخلفية",
        centerLogo = "الشعار / الأيقونة في المنتصف",
        selectFromGallery = "اختيار شعار من المعرض",
        customLogoSelected = "تم اختيار الشعار",
        removeCustomLogo = "إزالة",
        shareQr = "مشاركة",
        downloadQr = "تحميل",
        saveToHistory = "حفظ في السجل",
        savedToHistory = "تم حفظ الرمز في السجل.",
        qrSavedSuccess = "تم حفظ الرمز في المعرض!",
        shareChooserTitle = "مشاركة رمز QR",
        scanQrTitle = "مسح رمز QR",
        cameraPermissionTitle = "مطلوب إذن الكاميرا",
        cameraPermissionDesc = "يرجى منح إذن الوصول إلى الكاميرا لمسح الرموز في الوقت الفعلي.",
        grantPermission = "منح الإذن",
        flashOn = "تشغيل الفلاش",
        flashOff = "إيقاف الفلاش",
        scanFromGallery = "اختيار من المعرض",
        cameraAimHint = "وجه الكاميرا نحو رمز QR داخل الإطار",
        scannedResultTitle = "رمز QR الممسوح",
        copyText = "نسخ",
        copiedToClipboard = "تم النسخ إلى الحافظة",
        openInBrowser = "فتح في المتصفح",
        openAction = "فتح",
        createSimilar = "إنشاء مماثل",
        close = "إغلاق",
        noQrFoundInImage = "لم يتم العثور على رمز QR في الصورة",
        historyTitle = "السجل",
        historyScannedTab = "الممسوحة",
        historyCreatedTab = "المنشأة",
        searchInHistory = "بحث في السجل...",
        clearHistory = "مسح السجل",
        clearHistoryConfirmTitle = "مسح السجل",
        clearHistoryConfirmDesc = "هل أنت متأكد من رغبتك في حذف كافة السجلات؟",
        yesClear = "نعم، مسح",
        cancel = "إلغاء",
        emptyScannedHistory = "لا توجد رموز ممسوحة حتى الآن",
        emptyCreatedHistory = "لا توجد رموز منشأة حتى الآن",
        recordDeleted = "تم حذف السجل.",
        historyCleared = "تم مسح السجل."
    )

    private val hindiStrings = englishStrings.copy(
        appTitle = "क्यूआर कोड स्टूडियो",
        tabCreate = "बनाएं",
        tabScan = "स्कैन करें",
        tabHistory = "इतिहास",
        changeTheme = "थीम बदलें",
        changeLanguage = "भाषा चुनें",
        autoDetectLanguage = "स्वतः पहचान (सिस्टम)",
        selectLanguageTitle = "ऐप की भाषा चुनें",
        createQrTitle = "क्यूआर कोड जनरेटर",
        qrTypeUrl = "वेबसाइट",
        qrTypeText = "टेक्स्ट",
        qrTypeWifi = "वाई-फ़ाई",
        qrTypePhone = "फ़ोन",
        qrTypeEmail = "ईमेल",
        qrTypeSms = "एसएमएस",
        websiteUrlLabel = "वेबसाइट लिंक (URL)",
        textContentLabel = "टेक्स्ट सामग्री",
        wifiSsidLabel = "नेटवर्क का नाम (SSID)",
        wifiPasswordLabel = "वाई-फ़ाई पासवर्ड",
        wifiSecurityLabel = "सुरक्षा प्रकार",
        wifiNone = "कोई नहीं (खुला)",
        phoneNumberLabel = "फ़ोन नंबर",
        emailToLabel = "प्राप्तकर्ता ईमेल",
        emailSubjectLabel = "विषय",
        emailBodyLabel = "संदेश",
        smsPhoneLabel = "फ़ोन नंबर",
        smsMessageLabel = "एसएमएस संदेश",
        appearanceAndLogo = "दिखावट और लोगो",
        foregroundColor = "आगे का रंग",
        backgroundColor = "पृष्ठभूमि का रंग",
        centerLogo = "केंद्र लोगो / आइकन",
        selectFromGallery = "गैलरी से लोगो चुनें",
        customLogoSelected = "कस्टम लोगो चुना गया",
        removeCustomLogo = "हटाएं",
        shareQr = "साझा करें",
        downloadQr = "डाउनलोड करें",
        saveToHistory = "इतिहास में सहेजें",
        savedToHistory = "क्यूआर कोड इतिहास में सहेजा गया।",
        qrSavedSuccess = "क्यूआर कोड गैलरी में सहेजा गया!",
        shareChooserTitle = "क्यूआर कोड साझा करें",
        scanQrTitle = "क्यूआर कोड स्कैन करें",
        cameraPermissionTitle = "कैमरा अनुमति आवश्यक है",
        cameraPermissionDesc = "वास्तविक समय में क्यूआर कोड स्कैन करने के लिए कृपया कैमरा अनुमति दें।",
        grantPermission = "अनुमति दें",
        flashOn = "फ़्लैश ऑन",
        flashOff = "फ़्लैश ऑफ़",
        scanFromGallery = "गैलरी से चुनें",
        cameraAimHint = "क्यूआर कोड को फ्रेम के अंदर लाएं",
        scannedResultTitle = "स्कैन किया गया क्यूआर कोड",
        copyText = "कॉपी करें",
        copiedToClipboard = "क्लिपबोर्ड पर कॉपी किया गया",
        openInBrowser = "ब्राउज़र में खोलें",
        openAction = "खोलें",
        createSimilar = "समान बनाएं",
        close = "बंद करें",
        noQrFoundInImage = "छवि में कोई क्यूआर कोड नहीं मिला",
        historyTitle = "इतिहास",
        historyScannedTab = "स्कैन किए गए",
        historyCreatedTab = "बनाए गए",
        searchInHistory = "इतिहास में खोजें...",
        clearHistory = "इतिहास साफ़ करें",
        clearHistoryConfirmTitle = "इतिहास साफ़ करें",
        clearHistoryConfirmDesc = "क्या आप निश्चित रूप से सभी रिकॉर्ड हटाना चाहते हैं?",
        yesClear = "हाँ, साफ़ करें",
        cancel = "रद्द करें",
        emptyScannedHistory = "अभी तक कोई स्कैन किया गया क्यूआर कोड नहीं है",
        emptyCreatedHistory = "अभी तक कोई बनाया गया क्यूआर कोड नहीं है",
        recordDeleted = "रिकॉर्ड हटाया गया।",
        historyCleared = "इतिहास साफ़ किया गया।"
    )

    private val dutchStrings = englishStrings.copy(
        appTitle = "QR Code Studio",
        tabCreate = "Maken",
        tabScan = "Scannen",
        tabHistory = "Geschiedenis",
        changeTheme = "Thema wijzigen",
        changeLanguage = "Taal kiezen",
        autoDetectLanguage = "Automatisch detecteren (Systeem)",
        selectLanguageTitle = "Kies app-taal",
        createQrTitle = "QR-code generator",
        qrTypeUrl = "Website",
        qrTypeText = "Tekst",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Telefoon",
        qrTypeEmail = "E-mail",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Website link (URL)",
        textContentLabel = "Tekstinhoud",
        wifiSsidLabel = "Netwerknaam (SSID)",
        wifiPasswordLabel = "Wi-Fi wachtwoord",
        wifiSecurityLabel = "Beveiliging",
        wifiNone = "Geen wachtwoord",
        phoneNumberLabel = "Telefoonnummer",
        emailToLabel = "Ontvanger e-mail",
        emailSubjectLabel = "Onderwerp",
        emailBodyLabel = "Bericht",
        smsPhoneLabel = "Telefoonnummer",
        smsMessageLabel = "SMS-bericht",
        appearanceAndLogo = "Uiterlijk & Logo",
        foregroundColor = "Voorgrondkleur",
        backgroundColor = "Achtergrondkleur",
        centerLogo = "Logo / Icoon in het midden",
        selectFromGallery = "Kies logo uit galerij",
        customLogoSelected = "Aangepast logo geselecteerd",
        removeCustomLogo = "Verwijderen",
        shareQr = "Delen",
        downloadQr = "Downloaden",
        saveToHistory = "Opslaan in geschiedenis",
        savedToHistory = "QR-code opgeslagen in geschiedenis.",
        qrSavedSuccess = "QR-code opgeslagen in galerij!",
        shareChooserTitle = "QR-code delen",
        scanQrTitle = "QR-code scannen",
        cameraPermissionTitle = "Cameratoestemming vereist",
        cameraPermissionDesc = "Geef cameratoegang om QR-codes live te scannen.",
        grantPermission = "Toestemming geven",
        flashOn = "Flitser aan",
        flashOff = "Flitser uit",
        scanFromGallery = "Kiezen uit galerij",
        cameraAimHint = "Plaats de QR-code binnen het kader",
        scannedResultTitle = "Gescande QR-code",
        copyText = "Kopiëren",
        copiedToClipboard = "Gekopieerd naar klembord",
        openInBrowser = "Openen in browser",
        openAction = "Openen",
        createSimilar = "Vergelijkbare maken",
        close = "Sluiten",
        noQrFoundInImage = "Geen QR-code gevonden in afbeelding",
        historyTitle = "Geschiedenis",
        historyScannedTab = "Gescand",
        historyCreatedTab = "Gemaakt",
        searchInHistory = "Zoeken in geschiedenis...",
        clearHistory = "Geschiedenis wissen",
        clearHistoryConfirmTitle = "Geschiedenis wissen",
        clearHistoryConfirmDesc = "Weet u zeker dat u alle gegevens wilt wissen?",
        yesClear = "Ja, wissen",
        cancel = "Annuleren",
        emptyScannedHistory = "Nog geen gescande QR-codes",
        emptyCreatedHistory = "Nog geen gemaakte QR-codes",
        recordDeleted = "Item verwijderd.",
        historyCleared = "Geschiedenis gewist."
    )

    private val polishStrings = englishStrings.copy(
        appTitle = "Studio Kodów QR",
        tabCreate = "Utwórz",
        tabScan = "Skanuj",
        tabHistory = "Historia",
        changeTheme = "Zmień motyw",
        changeLanguage = "Wybierz język",
        autoDetectLanguage = "Wykryj automatycznie (System)",
        selectLanguageTitle = "Wybierz język aplikacji",
        createQrTitle = "Generator Kodów QR",
        qrTypeUrl = "Strona WWW",
        qrTypeText = "Tekst",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Telefon",
        qrTypeEmail = "E-mail",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Link do strony (URL)",
        textContentLabel = "Treść tekstu",
        wifiSsidLabel = "Nazwa sieci (SSID)",
        wifiPasswordLabel = "Hasło Wi-Fi",
        wifiSecurityLabel = "Typ zabezpieczeń",
        wifiNone = "Brak hasła",
        phoneNumberLabel = "Numer telefonu",
        emailToLabel = "Adres e-mail",
        emailSubjectLabel = "Temat",
        emailBodyLabel = "Wiadomość",
        smsPhoneLabel = "Numer telefonu",
        smsMessageLabel = "Wiadomość SMS",
        appearanceAndLogo = "Wygląd i Logo",
        foregroundColor = "Kolor kodu",
        backgroundColor = "Kolor tła",
        centerLogo = "Logo / Ikona na środku",
        selectFromGallery = "Wybierz logo z galerii",
        customLogoSelected = "Wybrano własne logo",
        removeCustomLogo = "Usuń",
        shareQr = "Udostępnij",
        downloadQr = "Pobierz",
        saveToHistory = "Zapisz w historii",
        savedToHistory = "Kod QR został zapisany w historii.",
        qrSavedSuccess = "Kod QR zapisany w galerii!",
        shareChooserTitle = "Udostępnij kod QR",
        scanQrTitle = "Skanuj kod QR",
        cameraPermissionTitle = "Wymagane uprawnienie do aparatu",
        cameraPermissionDesc = "Zezwól na dostęp do aparatu, aby skanować kody QR w czasie rzeczywistym.",
        grantPermission = "Zezwól",
        flashOn = "Latarka włączona",
        flashOff = "Latarka wyłączona",
        scanFromGallery = "Wybierz z galerii",
        cameraAimHint = "Skieruj aparat na kod QR w ramce",
        scannedResultTitle = "Zeskanowany kod QR",
        copyText = "Kopiuj",
        copiedToClipboard = "Skopiowano do schowka",
        openInBrowser = "Otwórz w przeglądarce",
        openAction = "Otwórz",
        createSimilar = "Utwórz podobny",
        close = "Zamknij",
        noQrFoundInImage = "Nie znaleziono kodu QR na obrazie",
        historyTitle = "Historia",
        historyScannedTab = "Zeskanowane",
        historyCreatedTab = "Utworzone",
        searchInHistory = "Szukaj w historii...",
        clearHistory = "Wyczyść historię",
        clearHistoryConfirmTitle = "Wyczyść historię",
        clearHistoryConfirmDesc = "Czy na pewno chcesz usunąć wszystkie wpisy w tej zakładce?",
        yesClear = "Tak, wyczyść",
        cancel = "Anuluj",
        emptyScannedHistory = "Brak zeskanowanych kodów QR",
        emptyCreatedHistory = "Brak utworzonych kodów QR",
        recordDeleted = "Wpis usunięty.",
        historyCleared = "Historia wyczyszczona."
    )

    private val indonesianStrings = englishStrings.copy(
        appTitle = "Studio Kode QR",
        tabCreate = "Buat",
        tabScan = "Pindai",
        tabHistory = "Riwayat",
        changeTheme = "Ganti Tema",
        changeLanguage = "Pilih Bahasa",
        autoDetectLanguage = "Deteksi Otomatis (Sistem)",
        selectLanguageTitle = "Pilih Bahasa Aplikasi",
        createQrTitle = "Pembuat Kode QR",
        qrTypeUrl = "Situs Web",
        qrTypeText = "Teks",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Telepon",
        qrTypeEmail = "Email",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Tautan Situs Web (URL)",
        textContentLabel = "Isi Teks",
        wifiSsidLabel = "Nama Jaringan (SSID)",
        wifiPasswordLabel = "Kata Sandi Wi-Fi",
        wifiSecurityLabel = "Tipe Keamanan",
        wifiNone = "Tanpa Sandi",
        phoneNumberLabel = "Nomor Telepon",
        emailToLabel = "Email Penerima",
        emailSubjectLabel = "Subjek",
        emailBodyLabel = "Pesan",
        smsPhoneLabel = "Nomor Telepon",
        smsMessageLabel = "Pesan SMS",
        appearanceAndLogo = "Tampilan & Logo",
        foregroundColor = "Warna Depan",
        backgroundColor = "Warna Latar",
        centerLogo = "Logo / Ikon Tengah",
        selectFromGallery = "Pilih Logo dari Galeri",
        customLogoSelected = "Logo Kustom Dipilih",
        removeCustomLogo = "Hapus",
        shareQr = "Bagikan",
        downloadQr = "Unduh",
        saveToHistory = "Simpan ke Riwayat",
        savedToHistory = "Kode QR disimpan ke riwayat.",
        qrSavedSuccess = "Kode QR berhasil disimpan ke galeri!",
        shareChooserTitle = "Bagikan Kode QR",
        scanQrTitle = "Pindai Kode QR",
        cameraPermissionTitle = "Izin Kamera Diperlukan",
        cameraPermissionDesc = "Izinkan akses kamera untuk memindai kode QR secara langsung.",
        grantPermission = "Beri Izin",
        flashOn = "Lampu Nyala",
        flashOff = "Lampu Mati",
        scanFromGallery = "Pilih dari Galeri",
        cameraAimHint = "Arahkan kode QR ke dalam bingkai",
        scannedResultTitle = "Kode QR Terpindai",
        copyText = "Salin",
        copiedToClipboard = "Disalin ke papan klip",
        openInBrowser = "Buka di Browser",
        openAction = "Buka",
        createSimilar = "Buat yang Serupa",
        close = "Tutup",
        noQrFoundInImage = "Tidak ada kode QR ditemukan pada gambar",
        historyTitle = "Riwayat",
        historyScannedTab = "Dipindai",
        historyCreatedTab = "Dibuat",
        searchInHistory = "Cari di riwayat...",
        clearHistory = "Hapus Riwayat",
        clearHistoryConfirmTitle = "Hapus Riwayat",
        clearHistoryConfirmDesc = "Apakah Anda yakin ingin menghapus semua rekaman di tab ini?",
        yesClear = "Ya, Hapus",
        cancel = "Batal",
        emptyScannedHistory = "Belum ada kode QR yang dipindai",
        emptyCreatedHistory = "Belum ada kode QR yang dibuat",
        recordDeleted = "Rekaman dihapus.",
        historyCleared = "Riwayat telah dibersihkan."
    )

    private val vietnameseStrings = englishStrings.copy(
        appTitle = "Studio Mã QR",
        tabCreate = "Tạo mã",
        tabScan = "Quét mã",
        tabHistory = "Lịch sử",
        changeTheme = "Đổi giao diện",
        changeLanguage = "Chọn ngôn ngữ",
        autoDetectLanguage = "Tự động phát hiện (Hệ thống)",
        selectLanguageTitle = "Chọn ngôn ngữ ứng dụng",
        createQrTitle = "Tạo mã QR",
        qrTypeUrl = "Trang web",
        qrTypeText = "Văn bản",
        qrTypeWifi = "Wi-Fi",
        qrTypePhone = "Điện thoại",
        qrTypeEmail = "Email",
        qrTypeSms = "SMS",
        websiteUrlLabel = "Liên kết trang web (URL)",
        textContentLabel = "Nội dung văn bản",
        wifiSsidLabel = "Tên mạng (SSID)",
        wifiPasswordLabel = "Mật khẩu Wi-Fi",
        wifiSecurityLabel = "Bảo mật",
        wifiNone = "Không có mật khẩu",
        phoneNumberLabel = "Số điện thoại",
        emailToLabel = "Email người nhận",
        emailSubjectLabel = "Chủ đề",
        emailBodyLabel = "Nội dung",
        smsPhoneLabel = "Số điện thoại",
        smsMessageLabel = "Nội dung SMS",
        appearanceAndLogo = "Giao diện & Logo",
        foregroundColor = "Màu mã QR",
        backgroundColor = "Màu nền",
        centerLogo = "Logo / Biểu tượng ở giữa",
        selectFromGallery = "Chọn logo từ thư viện ảnh",
        customLogoSelected = "Đã chọn logo tùy chỉnh",
        removeCustomLogo = "Xóa",
        shareQr = "Chia sẻ",
        downloadQr = "Tải về",
        saveToHistory = "Lưu vào lịch sử",
        savedToHistory = "Mã QR đã được lưu vào lịch sử.",
        qrSavedSuccess = "Mã QR đã được lưu vào thư viện ảnh!",
        shareChooserTitle = "Chia sẻ mã QR",
        scanQrTitle = "Quét mã QR",
        cameraPermissionTitle = "Cần quyền truy cập máy ảnh",
        cameraPermissionDesc = "Vui lòng cấp quyền máy ảnh để quét mã QR trực tiếp.",
        grantPermission = "Cấp quyền",
        flashOn = "Bật đèn",
        flashOff = "Tắt đèn",
        scanFromGallery = "Chọn từ thư viện",
        cameraAimHint = "Căn chỉnh mã QR vào trong khung",
        scannedResultTitle = "Kết quả quét mã QR",
        copyText = "Sao chép",
        copiedToClipboard = "Đã sao chép vào bộ nhớ tạm",
        openInBrowser = "Mở trong trình duyệt",
        openAction = "Mở",
        createSimilar = "Tạo mã tương tự",
        close = "Đóng",
        noQrFoundInImage = "Không tìm thấy mã QR nào trong ảnh",
        historyTitle = "Lịch sử",
        historyScannedTab = "Đã quét",
        historyCreatedTab = "Đã tạo",
        searchInHistory = "Tìm trong lịch sử...",
        clearHistory = "Xóa lịch sử",
        clearHistoryConfirmTitle = "Xóa lịch sử",
        clearHistoryConfirmDesc = "Bạn có chắc chắn muốn xóa toàn bộ bản ghi trong tab này?",
        yesClear = "Đồng ý xóa",
        cancel = "Hủy",
        emptyScannedHistory = "Chưa có mã QR nào được quét",
        emptyCreatedHistory = "Chưa có mã QR nào được tạo",
        recordDeleted = "Đã xóa bản ghi.",
        historyCleared = "Đã dọn dẹp lịch sử."
    )
}

val LocalAppStrings = staticCompositionLocalOf { LanguageManager.getStrings(AppLanguage.SYSTEM.code) }
